import Head from 'next/head'
import Header from '../../components/Header'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Instagram Clone App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* HEADER */}
      <Header />
      {/* FEED */}
      {/* MODAL */}
    </div>
  )
}
